### ISSUE TITLE
Make Lecture 12: RNNs

### ISSUE THREAD

**Issue by marikgoldstein** [harvard-ml-courses/cs281-scribe#32] opened 2017-10-31 14:54 UTC
Hi all, just a reminder to make a pull request together for the lecture 12 notes, RNNs. Sorry for the delay

@joshspeagle, Josh Speagle
@akgoldberg, Alexander Goldberg
@DanielScottEaton, Daniel Eaton
@marble999, George Han
@graulem, Moritz Graule

You'll want to:

Make sure you read the LaTeX Guide
Make your own fork (so you can make a pull request when submitting).
I already made a 12/ directory.
Place all of your added commands + libraries in pagesetup.sty in the main directory
I already added a ref in main.tex to 12/12.tex
Edit README.md to refer to the right place
Feel free to discuss on here or on ShareLatex if that's easier.
Make sure that main.tex compiles before submitting a pull request

**Comment by DanielScottEaton** [comment] 2017-11-01 14:04
Hey everyone, so I think the best thing to do would be to divide the tasks up to begin with. I think a fair division of labor would be for four of us to do the actual scribing and one to handle the administrative stuff with github and sharelatex. Below I have produced a rough outline of the lecture divided as equally as possible into four pieces, as well as listing the 'admin' role. Just comment below with a reproduction of the list with your name filled into the task that you want. If you decide to do the admin stuff, please fork the repo and set up a sharelatex as soon as you can. I'll take whatever task is left over after everyone fills in their names. Thanks Guys!

Admin - 
Start-before the first graph representation of an RNN - 
The first graph representation of an RNN - Before "Issues: Network Layers" - 
"Issues: Network Layers" - Before "How to use an RNN?" - 
"How to use an RNN?" - End - 

Also, your notes might be a bit different than mine, so if you need to clarify some of these sections just comment and I'll try to respond as soon as I can.

**Comment by GrauleM** [comment] 2017-11-01 14:57
Hi guys,

Thanks, Daniel. 


I set up a public ShareLatex here: https://www.sharelatex.com/project/59f9dec253d7fe35b052da33

and forked the repo.

Happy to help out with the other things as well though - just let me know.

Best, 
Moritz

**Comment by joshspeagle** [comment] 2017-11-01 15:30
Hey all -- I've actually dropped the class, so I won't be able to help out with this. Sorry!

**Comment by DanielScottEaton** [comment] 2017-11-01 15:37
ok, since we will only have four total, here's a new roster of roles:

admin - Moritz
Start- Before "Issues: Network Layers" - Daniel
"Issues: Network Layers" - Before "How to use an RNN?" -
"How to use an RNN?" - End -

I just claimed the merged first part of the lecture since it is the longest and I doubt anyone would sign up for it of their own will (:

**Comment by akgoldberg** [comment] 2017-11-01 16:23
I can take “Issues: Network Layers”!

**Comment by akgoldberg** [comment] 2017-11-01 16:24
I can take “Issues: Network Layers”! So roster of roles:

admin - Moritz
Start- Before "Issues: Network Layers" - Daniel
"Issues: Network Layers" - Before "How to use an RNN?" - Alex
"How to use an RNN?" - End -

**Comment by GrauleM** [comment] 2017-11-01 17:29
@marble999: George, just checking that you are still taking the class?

for everyone: if you add packages or make other changes to the style file (or any file that is not our main file), can you please mark those changes with 'xx'? that way I can go through them quickly afterwards. 

Thanks, 
Moritz

**Comment by marble999** [comment] 2017-11-01 18:05
Hi guys,

"How to use an RNN?" - End sounds great! To clarify, @DanielScottEaton: which parts of the lecture did you have in mind for this section? I'm thinking a description of how to use an RNN to classify, as well as the small bit at the end about using RNNs in language translation and speech recognition.

**Final Roster:**
admin - Moritz
Start- Before "Issues: Network Layers" - Daniel
"Issues: Network Layers" - Before "How to use an RNN?" - Alex
"How to use an RNN?" - End - George

**Comment by DanielScottEaton** [comment] 2017-11-01 18:10
@marble999 
Yah that works; I also think there was a brief digression on 'Greedy Search'. Idk if it's that important as it was included somewhat haphazardly at the end of the lecture. Up to you whether to bother with it. Either way what you are already planning on doing seems sufficient.

**Comment by GrauleM** [comment] 2017-11-06 16:33
Hey guys, can you ping me when you are all done?

@marble999 
@DanielScottEaton 
@akgoldberg

**Comment by akgoldberg** [comment] 2017-11-06 17:07
I’m all done!

**Comment by DanielScottEaton** [comment] 2017-11-06 18:32
Done!

**Comment by marikgoldstein** [comment] 2017-11-07 06:13
If done, please make a pull request.

**Comment by marble999** [comment] 2017-11-07 07:35
I'm done as well! @GrauleM

**Closed** 2017-11-09 05:59 UTC
